services:
    ras_flash_alert.alert_reporter:
        class: Ras\Bundle\FlashAlertBundle\Model\AlertReporter
        arguments:
            session: @Session

    ras_flash_alert.alert_publisher:
        class: Ras\Bundle\FlashAlertBundle\Model\AlertPublisher
        arguments:
            session: @Session

    ras_flash_alert.twig.alert_reporter_extension:
        class: Ras\Bundle\FlashAlertBundle\Twig\FlashAlertsExtension
        arguments:
            container: @service_container
        tags:
            - { name: twig.extension }

    ras_flash_alert.templating.alert_reporter_helper:
        class: Ras\Bundle\FlashAlertBundle\Templating\Helper\FlashAlertsHelper
        arguments:
            templating: @templating
            alertPublisher: @ras_flash_alert.alert_publisher
            options: %ras_flash_alerts.options%
        tags:
            - { name: templating.helper, alias: flashAlerts }