services:
    # models
    ras_flash_alert.alert_manager:
        class: Ras\Bundle\FlashAlertBundle\Model\AlertManager
        arguments:
            - "@Session"

    ras_flash_alert.alert_reporter:
        class: Ras\Bundle\FlashAlertBundle\Model\AlertReporter
        arguments:
            - "@ras_flash_alert.alert_manager"

    ras_flash_alert.alert_publisher:
        class: Ras\Bundle\FlashAlertBundle\Model\AlertPublisher
        arguments:
            - "@ras_flash_alert.alert_manager"

    # twig extensions
    ras_flash_alert.twig.flash_alerts_extension:
        class: Ras\Bundle\FlashAlertBundle\Twig\FlashAlertsExtension
        arguments:
            - "@service_container"
        tags:
            - { name: twig.extension }

    # template helpers
    ras_flash_alert.templating.flash_alerts_helper:
        class: Ras\Bundle\FlashAlertBundle\Templating\Helper\FlashAlertsHelper
        arguments:
            - "@templating"
            - "@ras_flash_alert.alert_publisher"
            - "%ras_flash_alerts.options%"
        tags:
            - { name: templating.helper, alias: flashAlerts }
