parameters:
#    ras_alert_notifications.example.class: Ras\Bundle\AlertNotificationsBundle\Example

services:
#    ras_alert_notifications.example:
#        class: %ras_alert_notifications.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
